"""add phone number

Revision ID: 92102c39b380
Revises: 61f3bebabfa6
Create Date: 2022-07-04 09:38:18.415426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92102c39b380'
down_revision = '61f3bebabfa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
